version: '3.4'  
  
services:  
  WebCryptosApi:  
    image:  ${DOCKER_REGISTRY}api  
    build:  
      context: .  
      dockerfile: Dockerfile  
    depends_on:  
      - sqlserver
  sqlserver:  
    image: mcr.microsoft.com/mssql/server
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "BigPassw0rd"
    volumes:
      - ./data/mssql:/var/opt/mssql3
    ports:
      - '1433:1433'
    expose: 
      - 1433